version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # This mounts your local code into the container for live-reloading
      - .:/app
    # The command for development uses uvicorn with --reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload