services:
  - type: web
    name: automl-api
    runtime: docker
    repo: https://github.com/ChinmayBansal010/AutoML
    region: singapore
    plan: free
    
    # This is the key change:
    rootDir: Api # Tells Render to look inside the 'Api' folder
    
    # The path is now relative to the rootDir
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    
    envVars:
      - key: STORAGE_DIR
        value: /var/data/automl_storage
        
    disk:
      name: automl-storage
      mountPath: /var/data/automl_storage
      sizeGB: 1